// dashboard/src/lib/components/Table.svelte
<script lang="ts" generics="T extends { id: string } & Record<string, unknown>">
  import type { Snippet } from 'svelte';

  type Column = {
    key: keyof T;
    label: string;
    render?: Snippet<[T[keyof T], string]>;
  };

  type Props = {
    columns: Array<Column>;
    rows: ReadonlyArray<{ node: T }>;
  };

  let { columns, rows }: Props = $props();
</script>

<table class="my-2 w-full">
  <thead class="py-2">
    <tr>
      {#each columns as column}
        <th class="p-1 text-left">{column.label}</th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each rows as row}
      <tr>
        {#each columns as column}
          <td class="p-1">
            {#if column.render}
              {@render column.render(row.node[column.key], row.node.id)}
            {:else}
              {row.node[column.key] ?? '---'}
            {/if}
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

// dashboard/app/components/Table/Table.tsx
import type { ReactNode } from 'react';

export type Column<T> = {
  key: keyof T;
  label: string;
  render?: (value: T[keyof T], id: string) => ReactNode;
};

export type TableProps<T> = {
  columns: Array<Column<T>>;
  edges: ReadonlyArray<{ node: T }>;
};

export function Table<T extends { id: string } & Record<string, unknown>>({
  columns,
  edges,
}: TableProps<T>) {
  return (
    <table className="my-2 w-full">
      <thead className="py-2">
        <tr>
          {columns.map((column) => (
            <th className="p-1 text-left">{column.label}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {edges.map((edge) => (
          <tr>
            {columns.map((column) => (
              <td key={column.key.toString()} className="p-1">
                {column.render
                  ? column.render(edge.node[column.key], edge.node.id)
                  : String(edge.node[column.key] ?? '---')}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
