// dashboard/src/lib/components/Header.svelte
<script lang="ts">
  import { auth } from '@/lib/stores/auth';
</script>

<header class="sticky top-0 py-2">
  <nav>
    {#if $auth.user}
      <span>$: {$auth.user}</span>
      <span>
        <button class="cursor-pointer" type="button" onclick={auth.logout}> (Logout) </button>
      </span>
    {:else}
      <a href="/signup">Sign up</a>/<a href="/signin">Sign in</a>
    {/if}
  </nav>
</header>

// dashboard/app/components/Header/Header.tsx
import { NavLink, useNavigate } from 'react-router';
import { useAuth } from '~/providers/AuthProvider';
export function Header() {
  const navigate = useNavigate();
  const { user, logout } = useAuth();

  async function handleLogout() {
    await logout();
    navigate('/');
  }

  return (
    <header className="sticky top-0 py-2">
      {user?.username ? (
        <nav>
          <span>$: {user?.username}</span>
          <span>
            <button className="cursor-pointer" type="button" onClick={handleLogout}>
              (Logout)
            </button>
          </span>
        </nav>
      ) : (
        <nav>
          <NavLink to="/signup">Sign up</NavLink>/<NavLink to="/signin">Sign in</NavLink>
        </nav>
      )}
    </header>
  );
}
